services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_DB: places
      POSTGRES_USER: roni
      POSTGRES_PASSWORD: roni123
    ports:
      - "9999:5432"

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant-db
    environment:
      QDRANT__SERVICE__HTTP_PORT: 6333
      QDRANT__SERVICE__GRPC_PORT: 6334
    ports:
      - "6333:6333"  # HTTP API
      - "6334:6334"  # gRPC API
